import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import './globals.css'
import NavBar from '@/src/common/NavBar'
import { ArrowDownIcon } from '@heroicons/react/20/solid'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${raleway.className} bg-stone-50`}>
        <NavBar />
        <main className='relative w-full h-screen'>
          {children}
        </main>

      </body>
    </html>
  )
}
